### ISSUE TITLE
Numbers support not working.

### ISSUE THREAD

**Issue by MaverickMartyn** [CaptainArbitrary/CompactWorkTab#48]
In the latest version, the mod no longer affects Numbers views.
According to another comment on the workshop page, the same is the case for Grouped Pawn Lists. It might be related.
~~Possibly related to #49, since shift-clicking to sort appears to work in Numbers views, when the Horizontal label option is chosen.~~

**Comment by jefferyharrell** [comment]
That's correct, Compact Work Tab no longer does anything to any UI other than the main Work tab. This was a deliberate design choice so as not to stomp on the user interfaces of other mods.

Can you please elaborate on what you mean about Grouped Pawns Lists? A screenshot would be terrific.

**Comment by MaverickMartyn** [comment]
I don't know, another user posted about that on the workshop page. Just wanted to mention it, since I thought it would be related.
It's a shame to hear that it's on purpose. Why does the workshop page indicate otherwise?

**Comment by jefferyharrell** [comment]
Probably because I'm not very good at writing or updating documentation. I'll have a look at it later today and clarify.

**Comment by MaverickMartyn** [comment]
That's fair. 😄 
Documentation is rarely the most fun part.
Any chance it could be expanded to affect Numbers then? I wouldn't mind doing it myself, I just have no idea where to start.
(I haven't looked through the code yet, but I have only very limited Rimworld modding experience.)

**Comment by jefferyharrell** [comment]
I spent like 🤏 this much time studying Numbers while I was working on my mod, just enough time to see that it's quite complicated. Rewriting how it draws column headers in the general case would be a big job, and one very likely to break the next time Numbers gets an update. So I made the choice just to leave it alone and let Numbers be Numbers.

If the Numbers author wants to use my algorithms to draw vertical or inclined column headers, he's more than welcome to use my code. It's permissively licensed.

**Comment by MaverickMartyn** [comment]
Thank you for the explanation. I really appreciate it.😃 
I'll probably pursue that direction then.
Numbers is awesome, but the labels are nigh-unreadable most of the time, and this seems like the ideal solution.
Closing as "not planned".
