### ISSUE TITLE
Column interactions not working (eg. sorting)

### ISSUE THREAD

**Issue by MaverickMartyn** [CaptainArbitrary/CompactWorkTab#49]
Sorting, as well as any other column actions, like shift-clicking to increase priority, are not working.
The issue seems limited to the 45° and the vertical variant.

**Comment by jefferyharrell** [comment]
Thanks for the report! This was fixed in version 1.2.2 released about 3 hours ago. Steam is notorious for not downloading updated mods in a prompt fashion, so go through the usual steps to force it and you should be all better.

**Comment by MaverickMartyn** [comment]
Awesome! Sorry about the unnecessary issue. Closing!

**Comment by MaverickMartyn** [comment]
Already fixed.
